#+STARTUP: fnadjust
#+TITLE: The Need for a Science of Logic
#+DATE: PHIL 4/880\nbsp |\nbsp November 9, 2021
#+AUTHOR: Colin McLear
#+LATEX_COMPILER: xelatex
#+BIBLIOGRAPHY: ~/Dropbox/Work/bibfile.bib
#+EXCLUDE_TAGS: noexport notes scrap todo
#+OPTIONS: ':t toc:nil  H:2
#+OPTIONS: prop:nil
#+cite_export: csl chicago-author-date-16th-edition.csl


* Categorialism

- Categorialism: :: existence or being has a structure, and the categories
  delineate that structure


- Q: Why do we need a new theory of categories? 
- A: Because prior theories have been inadequate
   1. Unsystematic in their delineation of the categories
   2. Subjective in their derivation of the categories


* Hegel's Criticism of Kant

+ Hegel rejects Kant's derivation of the categories in two ways:
   1. The specification of /which/ concepts designate or express categories is
      historical/empirical/unscientific -- a science of logic must be /presuppositionless/

      #+begin_quote
      Logic, on the contrary, cannot presuppose any of these forms of
      reflection, these rules and laws of thinking, for they are part of its
      content and they first have to be established within it (SL 23; 21:27)
      #+end_quote

   2. The origin/derivation/basis of the categories results in a kind of
      subjectivism or skepticism
      
      #+begin_quote
      The /critique of the forms of the understanding/ [i.e. the categories] has
      arrived precisely at this result, namely that such forms do /not apply to
      things in themselves/. This can only mean that they are in themselves
      something untrue. (SL 26; 21:30)
      #+end_quote

** Which Categories?

- Kant rejects Aristotle's presentation of the categories because it is
  "rhapsodic" in its method of specifying which concepts express or refer to
  categories -- what is needed is a principle that specifies /all/ the
  categories (completeness) and /only/ the categories (exclusiveness) 

  #+begin_quote
  [we need an account of the categories that] has not arisen rhapsodically
  from a haphazard search for pure concepts, of the completeness of which one
  could never be certain, since one would only infer it through induction,
  without reflecting that in this way one would never see why just these and
  not other concepts should inhabit the pure understanding. (A81/B106-7)
  #+end_quote

- Kant argues that we need a principled account based on reflection on the
  forms of judgment

  #+begin_quote
  Transcendental philosophy has the advantage but also the obligation to seek
  its concepts in accordance with a principle, since they spring pure and
  unmixed from the understanding, as absolute unity, and must therefore be
  connected among themselves in accordance with a concept or idea. Such a
  connection, however, provides a rule by means of which the place of each
  pure concept of the understanding and the completeness of all of them
  together can be determined a priori, which would otherwise depend upon whim
  or chance. (A67/B92)
  #+end_quote

- Hegel rejects Kant's solution (viz. reflection on the forms of judgment) for
  being equally unsystematic

  #+begin_quote
  It is well known that the Kantian philosophy made it very easy for itself in
  locating the categories. The /I/, the unity of self-consciousness, is quite
  abstract and entirely indeterminate. How is one then to arrive at the
  /determinations/ of the I, the categories? Fortunately, the /various forms of
  judgment/ are already listed empirically in ordinary logic. Now to judge is
  to /think/ a determinate object. The various forms of judgment that had
  already been enumerated thus provide the various /determinations of thought/.
  (EL Â§42A)
  #+end_quote

- Hegel's position suggests that he thinks Kant faces a dilemma:
   1. The reflected nature of the categories is merely historical in its
      reception of commonly accepted logical forms
   2. The reflected nature of the categories is experiential in that it
      requires a kind of intellectual experience of acts of the mind to which
      one attends and then from which one abstracts to form the relevant concepts


** On What Basis? 

- Hegel's second criticism concerns the /origin/ of the categories in the
  subject's judgmental activity

  #+begin_quote
  When Kant in the /Critique of Pure Reason/ (p. 83)[A58/B82], in connection
  with logic comes to discuss the old and famous question: /What is truth/?, he
  starts by /passing off/ as a triviality the nominal definition that it is the
  agreement of cognition with its subject matter – a definition which is of
  great, indeed of supreme value. If we recall this definition together with
  the fundamental thesis of transcendental idealism, namely that /rational
  cognition/ is incapable of comprehending /things in themselves/, that /reality/
  lies /absolutely/ outside /the concept/, it is then at once evident that such a
  /reason/, one which is incapable of /setting itself in agreement/ with its
  subject matter, and the /things in themselves/, such as are not in agreement
  with the rational concept – a concept that does not agree with reality and a
  reality that does not agree with the concept – that these are /untrue
  conceptions/. If Kant had measured the idea of an /intuitive understanding/
  against that first definition of truth, he would have treated that idea
  which expresses the required agreement, not as a figment of thought but
  rather as truth. (SL 523; 12:26)
  #+end_quote

   - This is an objection to Kant's position that is /internal/ or "immanent" to
     Kant's position itself
   - Relies on Kant's twin commitments regarding truth as agreement &
     God's intuitive intellect
      + The problem: the conception of the intuitive intellect entails that
        our categories may not apply to being as it fundamentally is (i.e. that
        the categories aren't really categories of /being/ but rather merely
        being for /us/)


** Reconstructing Hegel's Argument

1.  God's intuitive intellect represents non-discursively, and thus
    non-categorially (definition)
2.  God's intellectual intuition is in total/absolute/perfect agreement
    with its object (definition)
3.  \therefore God's non-categorial intellectual intuition constitutes an ultimate
   standard for truth (as agreement of a representation with its object) (1-2)
4.  God's intellect perfectly comprehends all things from their grounds
    (definition)
5.  \therefore God truly or perfectly accurately /non/-categorially represents what is
   metaphysically fundamental about all things (3-4)
6.  If (5) then it is possible that the intuited ways of being are not
    identical to those ways of being picked out by the discursive
    categories (assumption)
7.  \therefore It is possible that the categories, even when applied correctly, do not
   pick out the necessarily fundamental ways of being (5, 6)
8.  It cannot be possible that the categories, when correctly applied, do not
   pick out the necessarily fundamental ways of being (assumption)
9.  Contradiction (7, 8)
10. Therefore ...
